# config.yaml
data_root: data/RAVDESS_audio/processed

model:
  type: wav2vec2
  pretrained: facebook/wav2vec2-base-960h
  trainable: false
  use_weighted_sum: true

transformer:
  feature_dim: 768
  input_dim: 768
  num_layers: 2
  nhead: 4
  dim_feedforward: 512
  pool: cls
  dropout: 0.5

optimizer:
  lr: 5e-5
  weight_decay: 1e-4

training:
  batch_size: 32
  max_seq_len: 250
  adv_weight: 0.0
  lambda_grl: 1.0
  epochs: 30
  num_workers: 4

device: cuda
output_dir: logs